// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cross_sec_area": {
            "get": {
                "description": "Возвращает информацию о площади сечения шва на основе материала, типа сварки, катета(толщины), типа шва",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о площади сечения шва",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа сварки",
                        "name": "welding_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Значение катета(толщины)",
                        "name": "katet_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа шва",
                        "name": "seam_type_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CrossSecArea"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cutting_calculate": {
            "get": {
                "description": "Рассчитывает время, необходимое для резки металла по заданному периметру. Может работать в HTTP и Websocket режимах",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculations"
                ],
                "summary": "Рассчитать время резки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Периметр, мм.",
                        "name": "perimeter",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Количество врезок, шт.",
                        "name": "insertion_count",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Скорость резки, мм/с.",
                        "name": "cutting_speed",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Время врезки, сек.",
                        "name": "insertion_time",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"calculated time\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверно указаны параметры",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cutting_info": {
            "get": {
                "description": "Возвращает информацию о резке для заданной машины, материала, толщины и газа.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cutting_info"
                ],
                "summary": "Получение информации о резке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название машины",
                        "name": "machine_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Толщина материала",
                        "name": "tickness",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название газа",
                        "name": "gas",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CUTTING_INFO"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gases": {
            "get": {
                "description": "Возвращает информацию о режущем газе для заданной машины, материала",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cutting_info"
                ],
                "summary": "Получение информации о режущем газе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название машины",
                        "name": "machine_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Толщина",
                        "name": "tickness",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Gases"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/katets": {
            "get": {
                "description": "Возвращает информацию о типах сварки для заданного материала и типа сварки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о катетах(толщине) металла",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа сварки",
                        "name": "welding_type_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Katets"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/machines": {
            "get": {
                "description": "Возвращает информацию о станках предприятия",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cutting_info"
                ],
                "summary": "Получение информации о станках",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Machine"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/materials": {
            "get": {
                "description": "Возвращает информацию о материале по заданному станку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cutting_info"
                ],
                "summary": "Получение информации о материале",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название станка",
                        "name": "machine_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Materials"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/seam_type": {
            "get": {
                "description": "Возвращает информацию о типе шва по заданным материалу, типу сварки и катету(толщине)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о типе шва",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа сварки",
                        "name": "welding_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Катет(толщина) материала",
                        "name": "katet_value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SeamTypes"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tnsh": {
            "get": {
                "description": "Возвращает информацию о времени затрачиваемом на обработку одной единицы изделия на основании материала, типа сварки, катета(толщины), типа шва, площади сечения и диаметра проволоки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение времени затрачиваемого на одну штуку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа сварки",
                        "name": "welding_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Значение катета(толщины)",
                        "name": "katet_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа шва",
                        "name": "seam_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Площадь сечения",
                        "name": "area_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Диаметер проволоки",
                        "name": "diameter_value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tnsh"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/welding_materials": {
            "get": {
                "description": "Возвращает информацию о материале",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о материале используемом для сварочных работ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WeldingMaterials"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/welding_types": {
            "get": {
                "description": "Возвращает информацию о типах сварки для заданного материала",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о типе сварки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WeldingTypes"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wire_diameter": {
            "get": {
                "description": "Возвращает информацию о диаметре проволоки на основании материала, типа сварки, катета(толщины), типа шва, площади сечения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "welding_info"
                ],
                "summary": "Получение информации о диаметре проволоки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название материала",
                        "name": "material_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа сварки",
                        "name": "welding_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Значение катета(толщины)",
                        "name": "katet_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название типа шва",
                        "name": "seam_type_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Площадь сечения",
                        "name": "area_value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WireDiameterValues"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CUTTING_INFO": {
            "type": "object",
            "properties": {
                "avecuttingspeed": {
                    "type": "number"
                },
                "data_updated": {
                    "type": "boolean"
                },
                "insertiontime": {
                    "type": "number"
                },
                "maxcuttingspeed": {
                    "type": "number"
                },
                "mincuttingspeed": {
                    "type": "number"
                },
                "record_id": {
                    "type": "integer"
                }
            }
        },
        "models.CrossSecArea": {
            "type": "object",
            "properties": {
                "area_value": {
                    "type": "number"
                }
            }
        },
        "models.Gases": {
            "type": "object",
            "properties": {
                "gas_id": {
                    "type": "integer"
                },
                "gas_name": {
                    "type": "string"
                }
            }
        },
        "models.Katets": {
            "type": "object",
            "properties": {
                "katet_value": {
                    "type": "string"
                }
            }
        },
        "models.Machine": {
            "type": "object",
            "properties": {
                "machine_id": {
                    "type": "integer"
                },
                "machine_name": {
                    "type": "string"
                }
            }
        },
        "models.Materials": {
            "type": "object",
            "properties": {
                "material_name": {
                    "type": "string"
                }
            }
        },
        "models.SeamTypes": {
            "type": "object",
            "properties": {
                "seam_type_name": {
                    "type": "string"
                }
            }
        },
        "models.Tnsh": {
            "type": "object",
            "properties": {
                "tnsh_value": {
                    "type": "number"
                }
            }
        },
        "models.WeldingMaterials": {
            "type": "object",
            "properties": {
                "material_name": {
                    "type": "string"
                }
            }
        },
        "models.WeldingTypes": {
            "type": "object",
            "properties": {
                "welding_type_name": {
                    "type": "string"
                }
            }
        },
        "models.WireDiameterValues": {
            "type": "object",
            "properties": {
                "diameter_value": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
